// List of deprecated cipher suites that should not be used.
// Courtesy of https://ciphersuite.info/
// See API endpoint: {https://ciphersuite.info/api/cs/security/insecure/

export const INSECURE_CIPHER_SUITES = {
  TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x19",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_anon_EXPORT_WITH_RC4_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x17",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "RC4 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_3DES_EDE_CBC_SHA: {
    gnutls_name: "TLS_DH_ANON_3DES_EDE_CBC_SHA1",
    openssl_name: "ADH-DES-CBC3-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x1B",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "3DES EDE CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_anon_WITH_AES_128_CBC_SHA: {
    gnutls_name: "TLS_DH_ANON_AES_128_CBC_SHA1",
    openssl_name: "ADH-AES128-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x34",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 128 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_AES_128_CBC_SHA256: {
    gnutls_name: "TLS_DH_ANON_AES_128_CBC_SHA256",
    openssl_name: "ADH-AES128-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0x6C",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 128 CBC",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_AES_128_GCM_SHA256: {
    gnutls_name: "TLS_DH_ANON_AES_128_GCM_SHA256",
    openssl_name: "ADH-AES128-GCM-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xA6",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 128 GCM",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_AES_256_CBC_SHA: {
    gnutls_name: "TLS_DH_ANON_AES_256_CBC_SHA1",
    openssl_name: "ADH-AES256-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x3A",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 256 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_AES_256_CBC_SHA256: {
    gnutls_name: "TLS_DH_ANON_AES_256_CBC_SHA256",
    openssl_name: "ADH-AES256-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0x6D",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 256 CBC",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_AES_256_GCM_SHA384: {
    gnutls_name: "TLS_DH_ANON_AES_256_GCM_SHA384",
    openssl_name: "ADH-AES256-GCM-SHA384",
    hex_byte_1: "0x00",
    hex_byte_2: "0xA7",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 256 GCM",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_ARIA_128_CBC_SHA256: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x46",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "ARIA 128 CBC",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_ARIA_128_GCM_SHA256: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x5A",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "ARIA 128 GCM",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_ARIA_256_CBC_SHA384: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x47",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "ARIA 256 CBC",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_ARIA_256_GCM_SHA384: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x5B",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "ARIA 256 GCM",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_128_CBC_SHA1",
    openssl_name: "ADH-CAMELLIA128-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x46",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 128 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_128_CBC_SHA256",
    openssl_name: "ADH-CAMELLIA128-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xBF",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 128 CBC",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_128_GCM_SHA256",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x84",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 128 GCM",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_256_CBC_SHA1",
    openssl_name: "ADH-CAMELLIA256-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x89",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 256 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_256_CBC_SHA256",
    openssl_name: "ADH-CAMELLIA256-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xC5",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 256 CBC",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384: {
    gnutls_name: "TLS_DH_ANON_CAMELLIA_256_GCM_SHA384",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x85",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "CAMELLIA 256 GCM",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_DH_anon_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x1A",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_anon_WITH_RC4_128_MD5: {
    gnutls_name: "TLS_DH_ANON_ARCFOUR_128_MD5",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x18",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "RC4 128",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_anon_WITH_SEED_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "ADH-SEED-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x9B",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "anon",
    enc_algorithm: "SEED CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x0B",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DH",
    auth_algorithm: "DSS",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_DSS_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x0C",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "DSS",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x11",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DHE",
    auth_algorithm: "DSS",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DHE_DSS_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x12",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "DSS",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DHE_PSK_WITH_NULL_SHA: {
    gnutls_name: "TLS_DHE_PSK_NULL_SHA1",
    openssl_name: "DHE-PSK-NULL-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x2D",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DHE_PSK_WITH_NULL_SHA256: {
    gnutls_name: "TLS_DHE_PSK_NULL_SHA256",
    openssl_name: "DHE-PSK-NULL-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB4",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DHE_PSK_WITH_NULL_SHA384: {
    gnutls_name: "TLS_DHE_PSK_NULL_SHA384",
    openssl_name: "DHE-PSK-NULL-SHA384",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB5",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DHE_PSK_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_DHE_PSK_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x8E",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "PSK",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x14",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DHE",
    auth_algorithm: "RSA",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DHE_RSA_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x15",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "RSA",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x0E",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "DH",
    auth_algorithm: "RSA",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_DH_RSA_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x0F",
    protocol_version: "TLS",
    kex_algorithm: "DH",
    auth_algorithm: "RSA",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA: {
    gnutls_name: "TLS_ECDH_ANON_3DES_EDE_CBC_SHA1",
    openssl_name: "AECDH-DES-CBC3-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x17",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "anon",
    enc_algorithm: "3DES EDE CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_ECDH_anon_WITH_AES_128_CBC_SHA: {
    gnutls_name: "TLS_ECDH_ANON_AES_128_CBC_SHA1",
    openssl_name: "AECDH-AES128-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x18",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 128 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_anon_WITH_AES_256_CBC_SHA: {
    gnutls_name: "TLS_ECDH_ANON_AES_256_CBC_SHA1",
    openssl_name: "AECDH-AES256-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x19",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "anon",
    enc_algorithm: "AES 256 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_anon_WITH_NULL_SHA: {
    gnutls_name: "TLS_ECDH_ANON_NULL_SHA1",
    openssl_name: "AECDH-NULL-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x15",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "anon",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_anon_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_ECDH_ANON_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x16",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "anon",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_ECDSA_WITH_NULL_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x01",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "ECDSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_ECDSA_WITH_RC4_128_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x02",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "ECDSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_ECDSA_WITH_NULL_SHA: {
    gnutls_name: "TLS_ECDHE_ECDSA_NULL_SHA1",
    openssl_name: "ECDHE-ECDSA-NULL-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x06",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "ECDSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_ECDHE_ECDSA_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x07",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "ECDSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_PSK_WITH_NULL_SHA: {
    gnutls_name: "TLS_ECDHE_PSK_NULL_SHA1",
    openssl_name: "ECDHE-PSK-NULL-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x39",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_PSK_WITH_NULL_SHA256: {
    gnutls_name: "TLS_ECDHE_PSK_NULL_SHA256",
    openssl_name: "ECDHE-PSK-NULL-SHA256",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x3A",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_PSK_WITH_NULL_SHA384: {
    gnutls_name: "TLS_ECDHE_PSK_NULL_SHA384",
    openssl_name: "ECDHE-PSK-NULL-SHA384",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x3B",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_PSK_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_ECDHE_PSK_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x33",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "PSK",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_RSA_WITH_NULL_SHA: {
    gnutls_name: "TLS_ECDHE_RSA_NULL_SHA1",
    openssl_name: "ECDHE-RSA-NULL-SHA",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x10",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "RSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDHE_RSA_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_ECDHE_RSA_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x11",
    protocol_version: "TLS",
    kex_algorithm: "ECDHE",
    auth_algorithm: "RSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_RSA_WITH_NULL_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x0B",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "RSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_ECDH_RSA_WITH_RC4_128_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0x0C",
    protocol_version: "TLS",
    kex_algorithm: "ECDH",
    auth_algorithm: "RSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_GOSTR341112_256_WITH_28147_CNT_IMIT: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC1",
    hex_byte_2: "0x02",
    protocol_version: "TLS",
    kex_algorithm: "VKO GOSTR3410 2012 256",
    auth_algorithm: "IMIT",
    enc_algorithm: "28147 CNT",
    hash_algorithm: "GOST R 34.11-2012",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC1",
    hex_byte_2: "0x00",
    protocol_version: "TLS",
    kex_algorithm: "GOSTR341112",
    auth_algorithm: "256",
    enc_algorithm: "KUZNYECHIK CTR",
    hash_algorithm: "OMAC",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC1",
    hex_byte_2: "0x03",
    protocol_version: "TLS",
    kex_algorithm: "VKO GOSTR3410 2012 256",
    auth_algorithm: "L",
    enc_algorithm: "KUZNYECHIK MGM",
    hash_algorithm: "GOST R 34.11-2012",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC1",
    hex_byte_2: "0x01",
    protocol_version: "TLS",
    kex_algorithm: "VKO GOSTR3410 2012 256",
    auth_algorithm: "OMAC",
    enc_algorithm: "MAGMA CTR",
    hash_algorithm: "GOST R 34.11-2012",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x29",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "DES CBC 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x26",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "DES CBC 40",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x2A",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC2 CBC 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x27",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC2 CBC 40",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_EXPORT_WITH_RC4_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x2B",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC4 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_EXPORT_WITH_RC4_40_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x28",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC4 40",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_WITH_3DES_EDE_CBC_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x23",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "3DES EDE CBC",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_WITH_DES_CBC_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x22",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "DES CBC",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x1E",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_WITH_IDEA_CBC_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x25",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "IDEA CBC",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_KRB5_WITH_RC4_128_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x24",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC4 128",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_KRB5_WITH_RC4_128_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x20",
    protocol_version: "TLS",
    kex_algorithm: "KRB5",
    auth_algorithm: "KRB5",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_NULL_WITH_NULL_NULL: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x00",
    protocol_version: "TLS",
    kex_algorithm: "NULL",
    auth_algorithm: "NULL",
    enc_algorithm: "NULL",
    hash_algorithm: "NULL",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_PSK_WITH_NULL_SHA: {
    gnutls_name: "TLS_PSK_NULL_SHA1",
    openssl_name: "PSK-NULL-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x2C",
    protocol_version: "TLS",
    kex_algorithm: "PSK",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_PSK_WITH_NULL_SHA256: {
    gnutls_name: "TLS_PSK_NULL_SHA256",
    openssl_name: "PSK-NULL-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB0",
    protocol_version: "TLS",
    kex_algorithm: "PSK",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_PSK_WITH_NULL_SHA384: {
    gnutls_name: "TLS_PSK_NULL_SHA384",
    openssl_name: "PSK-NULL-SHA384",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB1",
    protocol_version: "TLS",
    kex_algorithm: "PSK",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_PSK_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_PSK_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x8A",
    protocol_version: "TLS",
    kex_algorithm: "PSK",
    auth_algorithm: "PSK",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_EXPORT_WITH_DES40_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x08",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "DES40 CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x06",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "RC2 CBC 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_EXPORT_WITH_RC4_40_MD5: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x03",
    protocol_version: "TLS EXPORT",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "RC4 40",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_PSK_WITH_NULL_SHA: {
    gnutls_name: "TLS_RSA_PSK_NULL_SHA1",
    openssl_name: "RSA-PSK-NULL-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x2E",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_PSK_WITH_NULL_SHA256: {
    gnutls_name: "TLS_RSA_PSK_NULL_SHA256",
    openssl_name: "RSA-PSK-NULL-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB8",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_PSK_WITH_NULL_SHA384: {
    gnutls_name: "TLS_RSA_PSK_NULL_SHA384",
    openssl_name: "RSA-PSK-NULL-SHA384",
    hex_byte_1: "0x00",
    hex_byte_2: "0xB9",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "PSK",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_PSK_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_RSA_PSK_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x92",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "PSK",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_WITH_DES_CBC_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x09",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "DES CBC",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1"],
  },

  TLS_RSA_WITH_NULL_MD5: {
    gnutls_name: "TLS_RSA_NULL_MD5",
    openssl_name: "NULL-MD5",
    hex_byte_1: "0x00",
    hex_byte_2: "0x01",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "NULL",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_WITH_NULL_SHA: {
    gnutls_name: "TLS_RSA_NULL_SHA1",
    openssl_name: "NULL-SHA",
    hex_byte_1: "0x00",
    hex_byte_2: "0x02",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_WITH_NULL_SHA256: {
    gnutls_name: "TLS_RSA_NULL_SHA256",
    openssl_name: "NULL-SHA256",
    hex_byte_1: "0x00",
    hex_byte_2: "0x3B",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.2"],
  },

  TLS_RSA_WITH_RC4_128_MD5: {
    gnutls_name: "TLS_RSA_ARCFOUR_128_MD5",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x04",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "MD5",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_RSA_WITH_RC4_128_SHA: {
    gnutls_name: "TLS_RSA_ARCFOUR_128_SHA1",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x05",
    protocol_version: "TLS",
    kex_algorithm: "RSA",
    auth_algorithm: "RSA",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },

  TLS_SHA256_SHA256: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0xB4",
    protocol_version: "TLS",
    kex_algorithm: "-",
    auth_algorithm: "SHA256",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA256",
    security: "insecure",
    tls_version: ["TLS1.3"],
  },

  TLS_SHA384_SHA384: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0xC0",
    hex_byte_2: "0xB5",
    protocol_version: "TLS",
    kex_algorithm: "-",
    auth_algorithm: "SHA384",
    enc_algorithm: "NULL",
    hash_algorithm: "SHA384",
    security: "insecure",
    tls_version: ["TLS1.3"],
  },

  TLS_SM4_CCM_SM3: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0xC7",
    protocol_version: "TLS",
    kex_algorithm: "-",
    auth_algorithm: "-",
    enc_algorithm: "SM4 CCM",
    hash_algorithm: "SM3",
    security: "insecure",
    tls_version: ["TLS1.3"],
  },

  TLS_SM4_GCM_SM3: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0xC6",
    protocol_version: "TLS",
    kex_algorithm: "-",
    auth_algorithm: "-",
    enc_algorithm: "SM4 GCM",
    hash_algorithm: "SM3",
    security: "insecure",
    tls_version: ["TLS1.3"],
  },

  DHE_RSA_AES_128_SHA: {
    gnutls_name: "",
    openssl_name: "",
    hex_byte_1: "0x00",
    hex_byte_2: "0x33",
    protocol_version: "TLS",
    kex_algorithm: "DHE",
    auth_algorithm: "PSK",
    enc_algorithm: "RC4 128",
    hash_algorithm: "SHA",
    security: "insecure",
    tls_version: ["TLS1.0", "TLS1.1", "TLS1.2"],
  },
};
